DEBUG 2021-10-01 14:04:18.199 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-10-01 14:04:18.199 UTC: 	 Running on: Linux lxplus766.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-10-01 14:04:18.199 UTC: 	 Executing command: 'status'
DEBUG 2021-10-01 14:04:18.200 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
ERROR 2021-10-01 14:04:18.250 UTC: 	 Error: crab_projects/crab_NLO_step3_VLQ_DIGIPremix/ is not a valid CRAB project directory.
ERROR 2021-10-01 14:04:18.250 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_NLO_step3_VLQ_DIGIPremix/ is not a valid CRAB project directory.
INFO 2021-10-01 14:04:18.259 UTC: 	 Log file is /afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/crab.log
