DEBUG 2021-09-23 14:06:52.920 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-23 14:06:52.920 UTC: 	 Running on: Linux lxplus7110.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-23 14:06:52.920 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-23 14:06:52.920 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
INFO 2021-09-23 14:06:52.922 UTC: 	 Will use CRAB configuration file submit_step2_SIM_crab.py
DEBUG 2021-09-23 14:06:52.922 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-09-23 14:06:52.923 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-09-23 14:06:52.923 UTC: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-09-23 14:06:52.923 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-09-23 14:06:52.935 UTC: 	 Log file is /afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab.log
DEBUG 2021-09-23 14:08:26.235 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-23 14:08:26.235 UTC: 	 Running on: Linux lxplus7110.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-23 14:08:26.235 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-23 14:08:26.235 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
INFO 2021-09-23 14:08:26.237 UTC: 	 Will use CRAB configuration file submit_step2_SIM_crab.py
DEBUG 2021-09-23 14:08:26.237 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-09-23 14:08:26.242 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-09-23 14:08:26.243 UTC: 	 Working area '/afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab_projects/crab_NLO_step2_VLQ_SIM' already exists 
Please change the requestName in the config file
ERROR 2021-09-23 14:08:26.243 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab_projects/crab_NLO_step2_VLQ_SIM' already exists 
Please change the requestName in the config file
INFO 2021-09-23 14:08:26.246 UTC: 	 Log file is /afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab.log
DEBUG 2021-09-23 14:18:43.821 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-23 14:18:43.821 UTC: 	 Running on: Linux lxplus7110.cern.ch 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-23 14:18:43.821 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-23 14:18:43.821 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
INFO 2021-09-23 14:18:43.823 UTC: 	 Will use CRAB configuration file submit_step2_SIM_crab.py
DEBUG 2021-09-23 14:18:43.823 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-09-23 14:18:43.869 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-09-23 14:18:43.870 UTC: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-09-23 14:18:43.870 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-09-23 14:18:43.876 UTC: 	 Log file is /afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab.log
DEBUG 2021-09-28 14:23:47.051 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-28 14:23:47.052 UTC: 	 Running on: Linux lxplus726.cern.ch 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-28 14:23:47.052 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-28 14:23:47.052 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
INFO 2021-09-28 14:23:47.053 UTC: 	 Will use CRAB configuration file submit_step3_DIGIPremix_crab.py
DEBUG 2021-09-28 14:23:47.054 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-09-28 14:23:47.117 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-09-28 14:23:47.136 UTC: 	 Working area '/afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab_projects/crab_NLO_step3_VLQ_DIGIPremix' already exists 
Please change the requestName in the config file
ERROR 2021-09-28 14:23:47.136 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab_projects/crab_NLO_step3_VLQ_DIGIPremix' already exists 
Please change the requestName in the config file
INFO 2021-09-28 14:23:47.213 UTC: 	 Log file is /afs/cern.ch/work/b/bregnery/public/VLQ/UL/CMSSW_10_6_19/src/NNLO_VLQ_PrivateSamples/CrabRunFiles/crab.log
DEBUG 2021-09-28 15:02:35.401 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-28 15:02:35.401 UTC: 	 Running on: Linux lxplus726.cern.ch 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-09-28 15:02:35.401 UTC: 	 Executing command: 'checkusername'
DEBUG 2021-09-28 15:02:35.477 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/bregnery/.crab3
DEBUG 2021-09-28 15:02:35.630 UTC: 	 Checking credentials
DEBUG 2021-09-28 15:02:35.630 UTC: 	 Found proxy file /tmp/x509up_u79777
DEBUG 2021-09-28 15:02:35.630 UTC: 	 Getting proxy life time left
DEBUG 2021-09-28 15:02:39.547 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -timeleft
 output : 603740

 error: 
 retcode : 0
DEBUG 2021-09-28 15:02:41.203 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u79777 -actimeleft
 output : 603738

 error: 
 retcode : 0
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Proxy lifetime 603740 secs is different from voms extension lifetime 603738 secs for proxy: /tmp/x509up_u79777
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Proxy valid for 167:42:18 hours
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Command use: checkusername
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Options use: []
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Instance is None
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Server base url is None
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Retrieving username ...
DEBUG 2021-09-28 15:02:41.204 UTC: 	 Retrieving username from CRIC...
DEBUG 2021-09-28 15:02:42.396 UTC: 	 username is bregnery
INFO 2021-09-28 15:02:42.397 UTC: 	 Username is: bregnery
